=== cardano-foundation/cf-lob-platform/blockchain_common/src/main/resources/api1_lob_blockchain_transaction_metadata_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Individual Transactions Schema",
  "definitions": {
    "countryCodePattern": {
      "type": "string",
      "pattern": "^[A-Z]{2}$"
    },
    "currencyIdPattern": {
      "type": "string",
      "pattern": "^ISO_4217:[A-Z]{3}$|^ISO_24165:[A-Z0-9]+(:[A-Z0-9]+)?$"
    },
    "bigDecimalPattern": {
      "type": "string",
      "pattern": "^[+-]?[0-9]+(\\.[0-9]+)?([eE][+-]?[0-9]+)?$"
    },
    "accountingPeriodPattern": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}$"
    },
    "timestampPattern": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
    }
  },
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "creation_slot": {
          "type": "integer",
          "minimum": 0
        },
        "version": {
          "type": "string"
        },
        "timestamp": {
          "$ref": "#/definitions/timestampPattern"
        }
      },
      "required": ["creation_slot", "version", "timestamp"]
    },
    "org": {
      "type": "object",
      "properties": {
        "country_code": {
          "$ref": "#/definitions/countryCodePattern"
        },
        "name": {
          "type": "string"
        },
        "tax_id_number": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "currency_id": {
          "$ref": "#/definitions/currencyIdPattern"
        }
      },
      "required": ["country_code", "name", "tax_id_number", "id", "currency_id"]
    },
    "type": {
      "type": "string",
      "enum": ["INDIVIDUAL_TRANSACTIONS"]
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date"
          },
          "number": {
            "type": "string"
          },
          "batch_id": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "CardCharge",
              "VendorBill",
              "CardRefund",
              "Journal",
              "FxRevaluation",
              "Transfer",
              "CustomerPayment",
              "ExpenseReport",
              "VendorPayment",
              "BillCredit"
            ]
          },
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "amount": {
                  "$ref": "#/definitions/bigDecimalPattern"
                },
                "event": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  },
                  "required": ["code", "name"]
                },
                "project": {
                  "type": "object",
                  "properties": {
                    "cust_code": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  },
                  "required": ["cust_code", "name"]
                },
                "cost_center": {
                  "type": "object",
                  "properties": {
                    "cust_code": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  },
                  "required": ["cust_code", "name"]
                },
                "document": {
                  "type": "object",
                  "properties": {
                    "number": {
                      "type": "string"
                    },
                    "currency": {
                      "type": "object",
                      "properties": {
                        "cust_code": {
                          "type": "string"
                        },
                        "id": {
                          "$ref": "#/definitions/currencyIdPattern"
                        }
                      },
                      "required": ["cust_code", "id"]
                    },
                    "vat": {
                      "type": "object",
                      "properties": {
                        "cust_code": {
                          "type": "string"
                        },
                        "rate": {
                          "$ref": "#/definitions/bigDecimalPattern"
                        }
                      }
                    },
                    "counterparty": {
                      "type": "object",
                      "properties": {
                        "cust_code": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        }
                      },
                      "required": ["cust_code", "type"]
                    }
                  },
                  "required": ["number", "currency"]
                },
                "id": {
                  "type": "string"
                },
                "fx_rate": {
                  "$ref": "#/definitions/bigDecimalPattern"
                }
              },
              "required": ["amount", "event", "id", "fx_rate", "document"]
            }
          },
          "accounting_period": {
            "$ref": "#/definitions/accountingPeriodPattern"
          }
        },
        "required": ["date", "number", "batch_id", "id", "type", "items", "accounting_period"]
      }
    }
  },
  "required": ["metadata", "org", "type", "data"]
}

=== cardano-foundation/cf-lob-platform/_backend-services/cf-lob-tx-submitter/data/soft-launch-dec-2024-prod/lob-txs-metadata-276841a1-0511-4e00-87a1-31067cd7e230-2024-11-28T12:31:36.210668Z-118092470443336965097.json
{"metadata":{"creation_slot":1,"version":"1.0","timestamp":"2024-11-28T12:31:36.072688Z"},"data":[{"date":"2023-10-25","number":"JOURNALCF-356","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"fb18d903f66b1f10d9742ed1d56f162b20d2091041bf66e5fdc1a87459b33d3c","type":"Journal","items":[{"amount":"16444.07","document":{"number":"JE-CF-0332","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"d795cfeae544d15923e308ed4d34fe03e075ea7923de35e89ac884aba0a24151","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.234351"},{"amount":"16444.07","document":{"number":"JE-CF-0332","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"591d551ad5bdb2a512812d394f59a0baeca83d9ab945ae7d46ca982de76d9af1","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.234351"}],"accounting_period":"2023-10"},{"date":"2023-11-10","number":"JOURNALCF-375","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"fbd63845c38525ed101e09706a0ef27cf33550f7afc1411d8c0fdbe165601eff","type":"Journal","items":[{"amount":"29.46","document":{"number":"JE-CF-0351","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"7f23a745f293b1ddfea424f2ccb78ab2993aec448079de63ee546e1f034769a1","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.26475715"},{"amount":"29.46","document":{"number":"JE-CF-0351","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"cdb25ae6bb06c2e26d96ea9bae58a48b035b50c6254fea9e849c0093985ee833","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.26475715"}],"accounting_period":"2023-11"},{"date":"2023-09-30","number":"JOURNALCF-287","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"fbde848af78c67d9ba903a1cb57f1f9fec1060669bb4e2da854466f2eaac683c","type":"Journal","items":[{"amount":"99708.86","document":{"number":"JE-CF-0263","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"9570a1d4ace9640e04f7acfb37c16098a73a9b9fd3cf17ce461ac8432555b66f","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.247455"},{"amount":"99708.86","document":{"number":"JE-CF-0263","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"1094288d32959f02d451224d7e8d1d0301f315e0945b4438d9d3dfe03f3d86cf","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.247455"}],"accounting_period":"2023-09"},{"date":"2023-09-30","number":"JOURNALCF-291","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"fcf41e12c3947c36313f83a7284b590856788107bafd900d3798dc6f075b583b","type":"Journal","items":[{"amount":"19984.03","document":{"number":"JE-CF-0267","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"a9dbe1f679a1594bc5700ae44fb138bdf2522b63e9af3afa479a61a9790de61e","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.274618"},{"amount":"19984.03","document":{"number":"JE-CF-0267","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"df6abcfb21ce9d68b5db97031a862c3a92951ec7a55a2731859520f570dadf78","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.274618"}],"accounting_period":"2023-09"},{"date":"2023-12-01","number":"JOURNALCF-453","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"fd234a1dad45dd78090c7e667afd451f97dac2c54e56ea80281f4ee0a7b59b14","type":"Journal","items":[{"amount":"86199.56","document":{"number":"JE-CF-0429","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"95f909f1cc7792cf4d2bb288cea561d62fcfcd15a9d8ce7a7deb04e952571e15","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.409389"},{"amount":"86199.56","document":{"number":"JE-CF-0429","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"99123b5d5e39abd0aee393fa40e226df941b8cbf1804d2a54219c97c094f2916","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.409389"}],"accounting_period":"2023-12"},{"date":"2023-12-01","number":"JOURNALCF-462","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"fdc1ae50a5c1d4e1544dc4350f89e836ead5474d5b79fb84851343a6ed32be61","type":"Journal","items":[{"amount":"96251.26","document":{"number":"JE-CF-0438","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"bcb906098d6a7d75435372860d0588fc62bd87cf275a300d7daa7666f806117b","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.410392"},{"amount":"96251.26","document":{"number":"JE-CF-0438","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"0bc6e0ec6b5c79fa98bcf7257c38380e52768a9a9e9ec5d97d32d39f77380961","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.410392"}],"accounting_period":"2023-12"},{"date":"2023-05-16","number":"JOURNALCF-159","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"fdf6393286677b57775389ca2cab8e3c1a06cd5cbc2befa6d4f4662f4e7ce70e","type":"Journal","items":[{"amount":"802.87","document":{"number":"JE-CF-0135","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"841c1dd9e587f33a49c89bf7bc6125ae628315f95529ad39ee0211f27130d0c2","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.329962"},{"amount":"120.43","cost_center":{"cust_code":"17","name":"Support"},"document":{"number":"JE-CF-0135","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"cb66ec115ac37ee97e1e8255b8ff9bd6b03c56c2c3463b518ad037064b5b99c0","event":{"code":"8180T0000","name":"Fees Expenses"},"fx_rate":"0.329962"},{"amount":"682.44","document":{"number":"JE-CF-0135","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"f7f029466db120f8c184cd6e23543c9bb9c38b090b3cd6e112c71498e17a905c","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.329962"}],"accounting_period":"2023-05"},{"date":"2023-03-31","number":"JOURNALCF-134","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"fe0e8e4d871db91041389a21269696900ff092802638a68c96bbf3ec9fac706a","type":"Journal","items":[{"amount":"110314.31","document":{"number":"JE-CF-0110","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"f6a3d7d42eaac6284d755cbb23dc6669707529ad2de2d2b83edbabcdb80fcdd3","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.331769"},{"amount":"110314.31","document":{"number":"JE-CF-0110","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"6ee29646c043fa41e716e44fe04a8d2e3bcd2f8dba788446223df88dd6e3d10d","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.331769"}],"accounting_period":"2023-03"},{"date":"2023-12-01","number":"JOURNALCF-396","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"fe144374eaf1a44ee491502e0162d3285938a8e5adc8ed8759cb2f06ea1848ce","type":"Journal","items":[{"amount":"4498.5","document":{"number":"JE-CF-0372","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"ce6d81a4f4d1e4a3865ab2a5882f4ba80331eb4ce9d106b95291be97ede57cdf","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.278957"},{"amount":"4498.5","document":{"number":"JE-CF-0372","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"2e1b49d727d0c623ef8f852b3e2c68d472017423a9a70bf13dadb3b835450423","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.278957"}],"accounting_period":"2023-12"},{"date":"2023-12-01","number":"JOURNALCF-450","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"feb89bcf73c36cdddfcde539040e347787dabd3e4afbbbd7e9dfbddd1f932d8f","type":"Journal","items":[{"amount":"88828.74","document":{"number":"JE-CF-0426","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"658365da9634f0f1f27785bb7d97a0e03c7731eb89e53ba3a7bf617b670b75bc","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.42221"},{"amount":"88828.74","document":{"number":"JE-CF-0426","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"4d9ed4c40a2b189c2c47ae0a892f8f957c64d6d223b7b4c2a348feaf95635bae","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.42221"}],"accounting_period":"2023-12"},{"date":"2023-06-30","number":"JOURNALCF-197","batch_id":"b7aecf9d517e68a169b8d9c7fd68eb77f68dec4ffbcf4f54f8935a46aaf08a5f","id":"ffd9ae0cf0620f17e55550ad9591167f5be3381c77472abe9a782f6e32fed024","type":"Journal","items":[{"amount":"108942.87","document":{"number":"JE-CF-0173","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"eed4345f37d54e22521ea45a0ef832cc1242c75abcea01f883e9a868b4595cb1","event":{"code":"W100T0000","name":"Crypto Transfer in"},"fx_rate":"0.319905"},{"amount":"108942.87","document":{"number":"JE-CF-0173","currency":{"cust_code":"ADA","id":"ISO_24165:ADA:HWGL1C2CK"}},"id":"42da5bb60ab3079f9ac1921e69602fcdd4338fc4008ab9c204a192998696850e","event":{"code":"T00008310","name":"Staking Reward Revenue"},"fx_rate":"0.319905"}],"accounting_period":"2023-06"}],"org":{"country_code":"CH","name":"Cardano Foundation","tax_id_number":"CHE-184477354","id":"75f95560c1d883ee7628993da5adf725a5d97a13929fd4f477be0faf5020ca94","currency_id":"ISO_4217:CHF"},"type":"INDIVIDUAL_TRANSACTIONS"}
